#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BedroomObjects {
    ClosetDoor = 66,
    UnderSamsBed = 67,
    Pot = 68,
    TopNightstandDrawer = 69,
    BottomNightstandDrawer = 70,
    PurpleScarfBedpost = 72,
    Door = 73,
    PajamaSam = 74,
    TopLeftBedKnob = 75,
    TopRightBedKnob = 76,
    BottomRightBedKnob = 77,
    BottomLeftBedKnob = 78,
    BooksOnShelf = 79,
    PaperNailedToDoor = 80,
    Poster = 81,
    CeilingLightFixture = 82,
    WallPosterPajamaMan = 83,
    ToyAirplane = 84,
    SamStStreetSign = 85,
    PajamaManNightLight = 86,
    HangingBaseballGlove = 87,
    HangingBaseballCap = 88,
    LampShade = 89,
    Calendar = 90,
    ToyTruck = 91,
    OnTopOfTheBed = 93,
    Pillow = 94,
    ComicBook = 95,
    ClosetDoorLeft = 97,
}

impl BedroomObjects {
    pub fn as_str(&self) -> &'static str {
        match self {
            BedroomObjects::ClosetDoor => "Closet Door",
            BedroomObjects::UnderSamsBed => "Under Sam's Bed",
            BedroomObjects::Pot => "Pot",
            BedroomObjects::TopNightstandDrawer => "Top Nightstand Drawer",
            BedroomObjects::BottomNightstandDrawer => "Bottom Nightstand Drawer",
            BedroomObjects::PurpleScarfBedpost => "Purple Scarf / Bedpost",
            BedroomObjects::Door => "Door",
            BedroomObjects::PajamaSam => "Pajama Sam",
            BedroomObjects::TopLeftBedKnob => "Top left bed Knob",
            BedroomObjects::TopRightBedKnob => "Top right bed Knob",
            BedroomObjects::BottomRightBedKnob => "Bottom right Bed Knob",
            BedroomObjects::BottomLeftBedKnob => "Bottom Left Bed Knob",
            BedroomObjects::BooksOnShelf => "Books On Shelf",
            BedroomObjects::PaperNailedToDoor => "Paper Nailed To Door",
            BedroomObjects::Poster => "Poster",
            BedroomObjects::CeilingLightFixture => "Ceiling Light Fixture",
            BedroomObjects::WallPosterPajamaMan => "Wall Poster (Pajama Man)",
            BedroomObjects::ToyAirplane => "Toy Airplane",
            BedroomObjects::SamStStreetSign => "SAM ST Street Sign",
            BedroomObjects::PajamaManNightLight => "Pajama Man Night Light",
            BedroomObjects::HangingBaseballGlove => "Hanging Baseball Glove",
            BedroomObjects::HangingBaseballCap => "Hanging Baseball Cap",
            BedroomObjects::LampShade => "Lamp Shade",
            BedroomObjects::Calendar => "Calendar",
            BedroomObjects::ToyTruck => "Toy Truck",
            BedroomObjects::OnTopOfTheBed => "On top of the bed",
            BedroomObjects::Pillow => "Pillow",
            BedroomObjects::ComicBook => "Comic Book",
            BedroomObjects::ClosetDoorLeft => "Closet Door (Left)",
        }
    }
}

impl TryFrom<u16> for BedroomObjects {
    type Error = ();

    fn try_from(v: u16) -> Result<Self, Self::Error> {
        match v {
            66 => Ok(BedroomObjects::ClosetDoor),
            67 => Ok(BedroomObjects::UnderSamsBed),
            68 => Ok(BedroomObjects::Pot),
            69 => Ok(BedroomObjects::TopNightstandDrawer),
            70 => Ok(BedroomObjects::BottomNightstandDrawer),
            72 => Ok(BedroomObjects::PurpleScarfBedpost),
            73 => Ok(BedroomObjects::Door),
            74 => Ok(BedroomObjects::PajamaSam),
            75 => Ok(BedroomObjects::TopLeftBedKnob),
            76 => Ok(BedroomObjects::TopRightBedKnob),
            77 => Ok(BedroomObjects::BottomRightBedKnob),
            78 => Ok(BedroomObjects::BottomLeftBedKnob),
            79 => Ok(BedroomObjects::BooksOnShelf),
            80 => Ok(BedroomObjects::PaperNailedToDoor),
            81 => Ok(BedroomObjects::Poster),
            82 => Ok(BedroomObjects::CeilingLightFixture),
            83 => Ok(BedroomObjects::WallPosterPajamaMan),
            84 => Ok(BedroomObjects::ToyAirplane),
            85 => Ok(BedroomObjects::SamStStreetSign),
            86 => Ok(BedroomObjects::PajamaManNightLight),
            87 => Ok(BedroomObjects::HangingBaseballGlove),
            88 => Ok(BedroomObjects::HangingBaseballCap),
            89 => Ok(BedroomObjects::LampShade),
            90 => Ok(BedroomObjects::Calendar),
            91 => Ok(BedroomObjects::ToyTruck),
            93 => Ok(BedroomObjects::OnTopOfTheBed),
            94 => Ok(BedroomObjects::Pillow),
            95 => Ok(BedroomObjects::ComicBook),
            97 => Ok(BedroomObjects::ClosetDoorLeft),
            _ => Err(()),
        }
    }
}